apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pecan.fullname" . }}-executor
  labels:
    {{- include "pecan.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.executor.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pecan.name" . }}-executor
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pecan.name" . }}-executor
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: check-rabbitmq
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "pecan.env.rabbitmq" . | nindent 12 }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pecan.rabbitmq.secretName" . }}
                  key: {{ include "pecan.rabbitmq.rabbitmqPasswordSecretKey" . }}            
        - name: check-postgresql
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            {{- include "pecan.env.postgresql" . | nindent 12 }}
            - name: PGDATABASE
              value: {{ .Values.betydb.betyDatabase | quote }}
            - name: PG_TABLE
              value: "yields"
            - name: BETYPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pecan.betydb.secretName" . }}
                  key: {{ include "pecan.betydb.betydbPasswordKey" . }}  
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.project }}/executor:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            {{- include "pecan.env.rabbitmq" . | nindent 12 }}
            {{- include "pecan.env.postgresql" . | nindent 12 }}
            {{- include "pecan.env.cluster" . | nindent 12 }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pecan.rabbitmq.secretName" . }}
                  key: {{ include "pecan.rabbitmq.rabbitmqPasswordSecretKey" . }}  
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "pecan.betydb.secretName" . }}
                  key: {{ include "pecan.betydb.betydbEncryptionSecretKey" . }}
            - name: BETYPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pecan.betydb.secretName" . }}
                  key: {{ include "pecan.betydb.betydbPasswordKey" . }}  
          resources:
            {{- toYaml .Values.executor.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
{{- if $.Values.persistence.existingClaim }}
            claimName: {{ $.Values.persistence.existingClaim }}
{{- else }}
            claimName: {{ include "pecan.fullname" . }}-data
{{- end }}
      {{- with .Values.executor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.executor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.executor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
