{{- if and .Values.initializeData }}
# do we want to add .Release.IsInstall to only run on install?
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pecan.fullname" . }}-load-data
  labels:
    {{- include "pecan.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "20"
spec:
  ttlSecondsAfterFinished: 1
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/name: {{ include "pecan.fullname" . }}-load-data
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      restartPolicy: Never
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: check-postgresql
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "pecan.env.postgresql" . | nindent 12 }}
      containers:
        - name: post-install-job
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            {{- include "pecan.env.postgresql" . | nindent 12 }}
            {{- include "pecan.env.cluster" . | nindent 12 }}
            - name: PSQL
              value: "psql -d {{ .Values.betydb.betyDatabase }} -q -t -c"
      volumes:
        - name: data
          persistentVolumeClaim:
{{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
{{- else }}
            claimName: {{ include "pecan.fullname" . }}-data
{{- end }}
{{- end }}
