apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pecan.fullname" . }}-web
  labels:
    {{- include "pecan.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs:
  - get
  - list
  - watch
  - update