{{- if .Values.models }}
{{- $fullname := include "pecan.fullname" . }}
{{- $labels := include "pecan.labels" . }}
{{- $rabbitmqEnv := include "pecan.env.rabbitmq" . }}
{{- range $key, $val := .Values.models }}
{{- if .enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}-model-{{ $key }}
  labels:
    {{ $labels | indent 4 }}