{{- if .Values.initializeData }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pecan.fullname" . }}-load-data
  labels:
    {{- include "pecan.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 1
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/name: {{ include "pecan.fullname" . }}-load-data
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      restartPolicy: Never
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: check-postgresql
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "pecan.env.postgresql" . | nindent 12 }}
            - name: PGDATABASE
              value: {{ .Values.betydb.betyDatabase | quote }}
            - name: PG_TABLE
              value: "yields"
            - name: BETYPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pecan.betydb.secretName" . }}
                  key: {{ include "pecan.betydb.betydbPasswordKey" . }}         
      containers:
        - name: add-data
          image: "{{ .Values.image.project }}/data:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            {{- include "pecan.env.postgresql" . | nindent 12 }}
            {{- include "pecan.env.cluster" . | nindent 12 }}
            - name: PSQL
              value: "psql -d {{ .Values.betydb.betyDatabase }} -q -t -c"
            - name: BETYPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pecan.betydb.secretName" . }}
                  key: {{ include "pecan.betydb.betydbPasswordKey" . }} 
      volumes:
        - name: data
          persistentVolumeClaim:
{{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
{{- else }}
            claimName: {{ include "pecan.fullname" . }}-data
{{- end }}
{{- end }}
