apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pecan.fullname" . }}-docs
  labels:
    {{- include "pecan.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - get