apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pecan.fullname" . }}-monitor
  labels:
    {{- include "pecan.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.monitor.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pecan.name" . }}-monitor
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pecan.name" . }}-monitor
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pecan.fullname" . }}-monitor
      automountServiceAccountToken: false
      initContainers:
        - name: check-rabbitmq
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "pecan.env.rabbitmq" . | nindent 12 }}
        - name: check-postgresql
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "pecan.env.postgresql" . | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.project }}/monitor:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "pecan.env.rabbitmq" . | nindent 12 }}
            {{- include "pecan.env.postgresql" . | nindent 12 }}
            {{- include "pecan.env.cluster" . | nindent 12 }}
            - name: RABBITMQ_MGMT_PATH
              value: {{ .Values.rabbitmq.ingress.path | default "/" | quote }}
          ports:
            - name: pecan-monitor
              containerPort: 9999
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: pecan-monitor
          readinessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}monitor/
              port: pecan-monitor
          resources:
            {{- toYaml .Values.monitor.resources | nindent 12 }}
      {{- with .Values.monitor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.monitor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.monitor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
